* mesa-minor-mode

An Emacs minor mode for use with the MESA stellar evolution code.

It makes it a bit easier to take advantage of the [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Tags.html#Tags][tag-related features]]
in Emacs when editing MESA inlists.  The default tag file will include
everything in the star_job, controls, and pgstar namelists.

* Installation
** Generate Tags File
You need to generate a TAGS file, which indexes information about the
MESA options.  A simple Bash script to do this is included as
maketags.sh.  There's only one command, so users of other shells
should have no trouble generalizing.  You may want to redo this step
when you upgrade MESA.
** Configure Emacs
Put the .el file in your load-path and then add
#+BEGIN_EXAMPLE
(require 'mesa-minor-mode)
#+END_EXAMPLE
to your Emacs init file.

* Usage
** Start the Mode
You can toggle the minor-mode manually with
#+BEGIN_EXAMPLE
M-x mesa-minor-mode
#+END_EXAMPLE
You can have Emacs start the minor-mode automatically when you edit a
file whose name starts with inlist, by adding something like
#+BEGIN_EXAMPLE
(setq auto-mode-alist  (cons '("/inlist[^/]*$" . mesa-minor-mode) auto-mode-alist))
#+END_EXAMPLE
to your Emacs init file.  (If you're already automatically starting a
major-mode to edit inlist files, you should probably have that
major-mode hook start up this minor mode.)

** Jump to/from a tag
This is the tags feature I use most when editing a MESA inlist.  The
command M-. will jump you to a variable's definition in the
appropriate .defaults file.  This lets you see the default value and
surrounding documentation. M-* will jump you back to your place in the
inlist.  For full details about using tags, read the Emacs docs.
